# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ $default-branch ]


permissions:
  contents: read

jobs:
  print_hello:

    runs-on: ubuntu-latest

    steps:
      - name: Print 
        run: echo "Hello World"