# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::297012935469:role/GithubAccess
          aws-region: ap-south-1
      - uses: actions/checkout@v3
      - name: Build Templates
        run: go run main.go
      - name: install dependencies
        run: pip3 install cfstack tabulate
      - name: Deploy Stacks
        run: python3 execute.py
  